@startuml
actor user as u
participant "ImageProcessor\n:ProcessingChain" as ip
participant "AstrometryCalibrator\n:ProcessingChain" as ac
participant "ObjectClassifier\n:ProcessingChain" as oc
participant "UnknownObjectLocator\n:ProcessingChain" as uol
u -> ip : Загрузка снимка
activate ip
ip -> ip : Чтение данных
alt Загруженный файл неподдерживаемого формата
ip -> u : Ошибка
else Формат файла допустимый
ip -> ip : Предобработка\nизображения
ip -> ac : Обработанное\nизображение
deactivate ip
activate ac
ref over ac
  Астрономическая
  калибровка
end ref
alt Результат астрономической калибровки - Failed
ac -> u : Ошибка
else
ac -> oc : Результат астрономической\nкалибровки
deactivate ac
activate oc
ref over oc
  Классификация
  объектов
end ref
alt Неизвестный объект не найден
oc -> u : Ошибка
else
oc -> uol : Результат астрономической\nкалибровки + классификации объектов
deactivate oc
activate uol
uol -> uol : Формирование результата:\nкоординаты объекта +\nобозначение на nизображении
uol -> u : Результат
deactivate uol
end
end
end
@enduml