@startuml

(*)--> "Классификация объектов\nна известные и нет"

if "По координатам RА и Dec найдена информация\nв астрономическом ежегоднике?" then
-->[Да] "Сравнение характеристик объекта\nс изображения и из ежегодника"
--> if "Характеристики совпали?" then
-->[Да] "Координаты известного объекта"
-->"Продолжение процесса обработки данных"
-right-> (*)
else
-->[Нет] "Данные координаты соответствуют\nискомому неизвестному объекту"
endif
else
-->[Нет] "Данные координаты соответствуют\nискомому неизвестному объекту"
--> (*)

@enduml